### ISSUE TITLE
github indeciso se precisa ou não de uma pasta /docs

### ISSUE THREAD

**Issue by antonioluppi** [tarrafahc/tarrafahc.github.io#3]
Páginas de organização ou pessoal são geradas somente a partir do master branch.

Não sei pq as páginas demoravam para serem atualizadas e pareciam bugadas ou não funcionando e sinceramente, n sei como deu certo no final. Inclusive recebi umemail reclamando da falta de uma pasta /docs https://help.github.com/articles/page-build-failed-missing-docs-folder/

O que não faz sentido pela documentação oficial do github pages.

**Comment by antonioluppi** [comment]
até agora, o site funciona do jeito que está

**Comment by Markkop** [comment]
mudei tudo e agora funciona (?)
